In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model

In [2]:
df = datasets.load_iris()
df.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [3]:
print(df.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [4]:
print(df.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [14]:
from sklearn.model_selection import train_test_split
x_df = pd.DataFrame(df.data, columns=df.feature_names)
x_df.head()
# x_df.shape

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
X_train, X_test, y_train, y_test = train_test_split(x_df, df.target, test_size=0.2)

In [17]:
X_train.shape

(120, 4)

In [12]:
len(y_train)

120

# Appling a classification algorithum

In [25]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, mean_squared_error
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [26]:
knn_predict = knn.predict(X_test)
print(knn_predict)

[0 1 2 0 2 1 1 0 1 1 1 2 2 0 1 0 1 1 1 0 0 2 2 2 0 2 1 2 2 2]


In [27]:
print(y_test)

[0 1 2 0 2 1 1 0 1 1 1 2 2 0 1 0 1 1 1 0 0 2 2 1 0 2 1 2 2 2]


In [28]:
print("Mean Squared Error - ", mean_squared_error(y_test , knn_predict))
accuracy = accuracy_score(y_test , knn_predict)

print("Accuracy Percentage :", accuracy*100, "%")

Mean Squared Error -  0.03333333333333333
Accuracy Percentage : 96.66666666666667 %


# Exporting the ML model

In [46]:
import pickle
filename = 'finalized_model.pkl'
pickle.dump(knn, open(filename, 'wb'))

# Testing the model

In [47]:
loaded_model = pickle.load(open(filename, 'rb'))
loaded_model.predict(X_test)

array([0, 1, 2, 0, 2, 1, 1, 0, 1, 1, 1, 2, 2, 0, 1, 0, 1, 1, 1, 0, 0, 2,
       2, 2, 0, 2, 1, 2, 2, 2])

In [45]:
loaded_model.predict([[6.5	,3.0	,5.8,	2.2]])[0]

C:\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


2

In [43]:
X_test

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
40                 5.0               3.5                1.3               0.3
64                 5.6               2.9                3.6               1.3
100                6.3               3.3                6.0               2.5
19                 5.1               3.8                1.5               0.3
120                6.9               3.2                5.7               2.3
84                 5.4               3.0                4.5               1.5
69                 5.6               2.5                3.9               1.1
8                  4.4               2.9                1.4               0.2
75                 6.6               3.0                4.4               1.4
52                 6.9               3.1                4.9               1.5
95                 5.7               3.0                4.2               1.2
113                5.7               2.5                5.0               2.0
126                6.2               2.8                4.8               1.8
13                 4.3               3.0                1.1               0.1
73                 6.1               2.8                4.7               1.2
17                 5.1               3.5                1.4               0.3
94                 5.6               2.7                4.2               1.3
82                 5.8               2.7                3.9               1.2
55                 5.7               2.8                4.5               1.3
35                 5.0               3.2                1.2               0.2
14                 5.8               4.0                1.2               0.2
149                5.9               3.0                5.1               1.8
117                7.7               3.8                6.7               2.2
83                 6.0               2.7                5.1               1.6
39                 5.1               3.4                1.5               0.2
131                7.9               3.8                6.4               2.0
96                 5.7               2.9                4.2               1.3
129                7.2               3.0                5.8               1.6
103                6.3               2.9                5.6               1.8
104                6.5               3.0                5.8               2.2

In [49]:
df.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [50]:
import skops.io as sio

ModuleNotFoundError: No module named 'skops'

In [51]:
!pip install skops

  Using cached skops-0.6.0-py3-none-any.whl (112 kB)
  Using cached scikit_learn-1.2.2-cp311-cp311-win_amd64.whl (8.3 MB)
  Using cached huggingface_hub-0.13.3-py3-none-any.whl (199 kB)
  Using cached tabulate-0.9.0-py3-none-any.whl (35 kB)
  Using cached packaging-23.0-py3-none-any.whl (42 kB)


ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python311\\Scripts\\tabulate.exe' -> 'C:\\Python311\\Scripts\\tabulate.exe.deleteme'


[notice] A new release of pip available: 22.3 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
  Using cached PyYAML-6.0-cp311-cp311-win_amd64.whl (143 kB)
  Using cached scipy-1.10.1-cp311-cp311-win_amd64.whl (42.2 MB)
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
  Using cached charset_normalizer-3.1.0-cp311-cp311-win_amd64.whl (96 kB)
  Using cached urllib3-1.26.15-py2.py3-none-any.whl (140 kB)


In [53]:
import skops.io as sio

ModuleNotFoundError: No module named 'skops'